name: gohome
description: A compass application that point you home.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  cupertino_icons: ^0.1.2
  location: ^2.5.4
  flutter_compass: ^0.3.2
  flutter_bloc: ^3.2.0
  hydrated_bloc: ^3.0.0
  equatable: ^1.1.1
  after_layout: ^1.0.7+2
  flutter_driving_directions: ^0.0.1






dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^4.0.0
  mockito: ^4.1.1
  flutter_native_splash: ^0.1.9



flutter:


  uses-material-design: true

  assets:
    - i18n/en.json
    - i18n/fr.json
    - i18n/zh.json
    - i18n/ar.json
    - assets/images/
